---
date: "`r Sys.Date()`"
email: gotting@wisc.edu
title: "CV"
author: Kirsten Gotting
github: kirstengott
#phone: "971-221-3367"
web: kirstengotting.com
output: 
  pdf_document:
    template: svm-r-markdown-templates/svm-latex-cv.tex
fontsize: 11pt
geometry: margin=1in
mainfont: 14pt
fontfamily: arev
#fontfamilyoptions: sc, osf
linkcolor: blue
urlcolor: blue
bibliography: publications.bib
header-includes:
   - \usepackage{hanging}
   - \usepackage{setspace}\singlespacing

---

\linespread{1.0}

# Education

M.S. Genetics, University of Wisconsin Madison, Laboratory of Genetics \hfill 2019

M.S. Biology, University of Oregon, Department of Biology  \hfill 2014

B.A. Biology, University of Oregon, Department of Biology \hfill 2013

# Research Experience  

Graduate Researcher, Currie Lab, University of Wisconsin Madison \hfill 2018 - Present


- Sequenced, assembled and annotated 18 genomes of *Escovopsis* for comparative genomics. 

- Performed field work to obtain increased sampling of *Escovopsis*


Bioinformatics Intern, Sánchez Lab, Stowers Institute for Medical Research \hfill 2014

- Developed a self-documenting RNA-seq analysis pipeline for transcriptomics from non-model organisms.

- Created interactive data analysis applications.


Undergraduate Research Assistant, Selker Lab, University of Oregon \hfill 2012

- Created \textit{Neurospora crassa} mutants as part of a forward genetics screen selecting for defects in methylation.

# Employment

Bioinformaticist, Sánchez Lab, Stowers Institute for Medical Research \hfill 2014 – 2017

- Collaborated with scientists to analyze and interpret next generation sequencing data.


Line/Lab Assitant,  Zebrafish International Resource Center \hfill 2010 - 2013

- Worked to maintain and propagate zebrafish lines for shipping to research labs.


# Publications

\begin{hangparas}{.25in}{1}

\textbf{Gotting, K.}, May, D. S., Khadempour, L., Berasategui Lopez, A., Viaurre Montoya, Q., Sandstrom, S., Carlson, C., Schultz, T., Rodriguez, A., Tallerico Pupo, M., Bugni, T., Gerardo, N. M., Currie, C. R. “Genomic Diversification of the Parasite Escovopsis across the Evolutionary History of the Attine Ant-Microbe Symbiosis.” \textit{In Prep}.

Francoeur, C. B., Khadempour, L., Moreira-Soto, R.D., \textbf{Gotting, K.}, Book, A.J., Pinto-Tomás, A.A., Keefover-Ring, K., and Currie, C.R. "Bacteria contribute to plant secondary compound degradation in a generalist herbivore system." \textit{mBio} (2020): 865212.


Klocko, A.D., Summers, C.A., Glover, M.L., Parrish, R., Storck, W.K., McNaught, K.J., Moss, N., \textbf{Gotting, K.}, Stewart, A., Marrison, A.M., Payne, L., Hatakeyama, S., Selker, E.U. (2020) "Selection and characterization of mutants defective in DNA methylation in \textit{Neurospora crassa}." \textit{Genetics}.

Wang, W., Hu, C., Zeng, A., Gibbon, D., Hu, D., \textbf{Gotting, K.}, Granillo Ortega, A., Wang, Y., Robb, S., Schnittker, R., Zhang, S., Alegre, D., Li, H., Ross, E., Zhang, N., Brunet, A., Sánchez Alvarado A. (2020) "Changes in injury-responsive enhancers shape regenerative capacities in vertebrates." \textit{Science} 369, no. 6508.


Zhang S., Guo L., Guerrero-Hernández C., Ross E.J., \textbf{Gotting, K.}, McKinney S.A., Wang W., Xiang Y., Hawley S.R., and Sánchez Alvarado A. (2018) "A nuclear hormone receptor and lipid metabolism axis are required for the maintenance and regeneration of reproductive organs." \textit{bioRxiv}: 279364.

Davies, E.L., Lei K., Seidel C.W., Kroesen A.E., McKinney S.A., Guo L., Robb S.M.C., Ross E.J., \textbf{Gotting, K.}, and Sánchez Alvarado A. (2017) ”Embryonic origin of adult stem cells required for tissue homeostasis and regeneration.” \textit{eLife} 6: e21052.

Luttrell, S.M., \textbf{Gotting, K.}, Ross E.J., Sánchez Alvarado A., and Swalla B.J. (2016) ”Head Regeneration in Hemichordates Is Not a Strict Recapitulation of Development.” \textit{Developmental Dynamics}. 

Lei, K., Vu H.T., Mohan R.D., McKinney S.A., Seidel C.W., Alexander R., \textbf{Gotting, K.}, Workman J.L., and Sánchez Alvarado, A. (2016) ”Egf Signaling Directs Neoblast Repopulation by Regulating Asymmetric Cell Division in Planarians.” \textit{Developmental Cell} 38, no. 4: 413-429.

Robb, S., \textbf{Gotting, K.}, Ross, E.J., and Sánchez Alvarado, A. (2015) ”SmedGD 2.0: The Schmidtea mediterranea genome database.” \textit{genesis} 53, no. 8: 535-546.

\end{hangparas} 

# Mentoring
## University of Wisconsin Madison

- Hezekiah Gilles \hfill Fall 2019 - Present

- Soleil Young \hfill Spring 2019 - Present

# Teaching Experience

## University of Wisconsin - Madison

- Teaching Assistant, **General Genetics 2** \hfill Spring 2019

## Cold Spring Harbor Laboratory

- Teaching Assistant, **Programming for Biology** \hfill 2018, 2019, 2020**

## University of Oregon

- Graduate Teaching Fellow, **Cells** \hfill Fall 2013

- Undergraduate Teaching Assistant, **Evolution, Diversity & Ecology** \hfill Spring 2013



# Departmental Service

- Genetics Diversity Committee \hfill 2020 - present

- J.F. Crow Institute Evolution Coordinating Committee \hfill 2020 - present

  - -Diversity Committee Co-Chair 

- Genetics Admissions Committee \hfill 2019

- Genetics Graduate Student Committee \hfill 2018 - 2019

- Genetics Retreat Committee \hfill 2018 - 2019


# Leadership

## University of Wisconsin

- Co-chair, **ComBEE** (Computational Biology, Ecology, and Evolution) \hfill 2018 - Present
  + Organized monthly speaker series and coding working and learning groups.

- R Study Group Leader, **ComBEE** \hfill Spring 2018

  + Led a coding study group to teach the R programming language. 

## The Stowers Institute for Medical Research

- Organizer/Founder, **UO Data Working Group** \hfill 2014 - 2017

  + Organized and led a learning and working group for junior bioinformaticists.

# Workshops and Courses

## University of Wisconsin Madison Delta Program on Integrating Research, Teaching and Learning

- Fundamentals of Online Learning and Teaching \hfill 2020

- Teaching college students on the autism spectrum \hfill 2018

# Outreach

## Currie Lab Leaf-Cutter Ant Display Colony

- Organizer; Activity Leader, **UW-Madison Science Expeditions** \hfill 2018; 2019

- Organizer and Activity Leader, **Wisconsin Science Festival** \hfill 2018


# Conferences Attended

Mycological Society of America \hfill 2019, 2020

Beneficial Microbe \hfill 2018

Madison Microbiome Meeting \hfill 2018

useR! \hfill 2016

North American Planarian Meeting \hfill 2015


# Presentations

## The University of Wisconsin Madison

Genomic diversification of the parasite \textit{Escovopsis} across the evolutionary history of the fungus-growing ant-microbe symbiosis

- UW-Madison Evolution Seminar Series \textbf{Talk} \hfill 2020

- Mycological Society of America \textbf{Poster} \hfill 2020 

- Laboratory of Genetics Graduate Seminar Series \textbf{Talk} \hfill 2020

- Beneficial Microbes** \hfill 2020

- Kenneth B. Raper Symposium, Department of Bacteriogy \textbf{Poster} \hfill 2019

## The Stowers Institute for Medical Research

- Designing an RNA-seq Pipeline for Non-Model Organisms \textbf{Talk} \hfill 2014

# Skills


## Computational
- Linux/Unix
- Parallel Computing 
- Git
- MySQL

## Programming Languages
- R
- Python
- Bash

## Data Analytics

- Phylogenomics
- Comparative Genomics
- RNA-seq
- Genome Annotation
- Differential Isoform
- Gene Ontology Enrichment 
- Motif Finding
- MudPIT Proteomics 
- Bioconductor
- RShiny

# Languages
- English (native)
- Spanish (conversational)




**denotes events cancelled due to COVID19
